(()=>{
'use strict';
const $=s=>document.querySelector(s);
const game=$('#game'),batScene=$('#batScene'),flightScene=$('#flightScene'),overlay=$('#overlay');
const tira=$('#tira'),tiraWrap=$('#tiraWrap'),pitcher=$('#pitcher'),pitchBall=$('#pitchBall'),trail=$('#trail'),swingBtn=$('#swingBtn'),hint=$('#hint'),batStatus=$('#batStatus');
const impactBurst=$('#impactBurst'),flash=$('#flash'),kakiin=$('#kakiin'),flightBall=$('#flightBall'),ballComet=$('#ballComet'),pickups=$('#pickups');
const distanceNum=$('#distanceNum'),scoreNum=$('#scoreNum'),pickupText=$('#pickupText'),landingDust=$('#landingDust'),landText=$('#landText');
const intro=$('#intro'),result=$('#result'),startBtn=$('#startBtn'),resultDistance=$('#resultDistance'),resultScore=$('#resultScore'),resultMeat=$('#resultMeat'),resultStar=$('#resultStar');
const farClouds=$('#farClouds'),mountainLayer=$('#mountainLayer'),cityLayer=$('#cityLayer'),treeLayer=$('#treeLayer'),groundLayer=$('#groundLayer'),steerHint=$('#steerHint');
let phase='idle',raf=0,pitchStart=0,pitchDur=1050,pitchP=0,score=0,meat=0,stars=0,distance=0,flightStart=0,flightDur=6400,targetX=.5,targetY=.54,ballX=.5,ballY=.54,lastPointer=null,audioCtx=null,pickupData=[];
const frames=[['0%','0%'],['33.333%','0%'],['66.667%','0%'],['100%','0%'],['0%','100%'],['33.333%','100%'],['66.667%','100%'],['100%','100%']];
function frame(i){const p=frames[i]||frames[0];tira.style.backgroundPosition=p[0]+' '+p[1]}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function tone(freq=440,time=.08,type='sine',vol=.05){try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+time);o.stop(audioCtx.currentTime+time)}catch(e){}}
function hitSound(){tone(520,.07,'square',.07);setTimeout(()=>tone(830,.11,'triangle',.06),45);setTimeout(()=>tone(1180,.16,'sine',.04),92)}
function resetAnim(el,cls){el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function setPhase(p){phase=p;if(batStatus)batStatus.textContent=p==='pitch'?'PITCH!':p==='hit'?'IMPACT!':p==='flight'?'FLYING!':p==='land'?'LANDING':'READY'}
function pitchPos(p){const g=game.getBoundingClientRect(),pr=pitcher.getBoundingClientRect(),tr=tiraWrap.getBoundingClientRect();const sx=(pr.left-g.left)+pr.width*.73,sy=(pr.top-g.top)+pr.height*.52,ex=(tr.left-g.left)+tr.width*.34,ey=(tr.top-g.top)+tr.height*.50;const x=sx+(ex-sx)*p,y=sy+(ey-sy)*p-Math.sin(Math.PI*p)*24,scale=.52+p*.58;pitchBall.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`;const dx=x-sx,dy=y-sy,len=Math.hypot(dx,dy);trail.style.left=sx+'px';trail.style.top=sy+'px';trail.style.width=Math.max(20,len-20)+'px';trail.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;trail.style.opacity=String(Math.min(.72,p*.9))}
function pitchLoop(now){if(phase!=='pitch')return;pitchP=Math.max(0,Math.min(1,(now-pitchStart)/pitchDur));pitchPos(pitchP);if(pitchP>=1){miss('見逃し！');return}raf=requestAnimationFrame(pitchLoop)}
async function startPitch(){setPhase('pitch');score=meat=stars=distance=0;scoreNum.textContent='0';distanceNum.textContent='0m';targetX=ballX=.5;targetY=ballY=.54;pickupData=[];pickups.innerHTML='';frame(0);tiraWrap.className='breathe';pitchBall.style.display='block';pitchBall.style.opacity='1';trail.style.opacity='0';swingBtn.disabled=true;hint.style.opacity='1';hint.textContent='ピッチャー、振りかぶった！';resetAnim(pitcher,'windup');await wait(250);frame(1);tiraWrap.className='prep';await wait(170);swingBtn.disabled=false;hint.textContent='いまだと思ったらタップ！';pitchStart=performance.now();pitchPos(0);cancelAnimationFrame(raf);raf=requestAnimationFrame(pitchLoop)}
function doSwing(){if(phase!=='pitch')return;const error=Math.abs(pitchP-.86);swingBtn.disabled=true;if(error>.17){frame(2);setTimeout(()=>frame(3),55);tiraWrap.className='impact';tone(155,.09,'sawtooth',.04);setTimeout(()=>miss(pitchP<.86?'早い！':'遅い！'),230);return}cinematicHit(error)}
async function miss(text){if(phase==='idle')return;cancelAnimationFrame(raf);setPhase('idle');pitchBall.style.display='none';trail.style.opacity='0';frame(6);tiraWrap.className='';hint.textContent=text+'　もう一回！';tone(170,.12,'triangle',.04);await wait(650);intro.style.display='block';result.style.display='none';startBtn.textContent='⚾ もう一球！';overlay.classList.remove('hidden')}
async function cinematicHit(error){
 cancelAnimationFrame(raf);setPhase('hit');trail.style.opacity='0';hint.style.opacity='0';
 frame(2);tiraWrap.className='prep';await wait(42);frame(3);await wait(46);frame(4);tiraWrap.className='impact';
 resetAnim(flash,'go');resetAnim(impactBurst,'go');resetAnim(kakiin,'go');resetAnim(batScene,'shake');hitSound();
 if(kakiin.animate)kakiin.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.32) rotate(-10deg)'},{opacity:1,offset:.14,transform:'translate(-50%,-50%) scale(1.2) rotate(-5deg)'},{opacity:1,offset:.68,transform:'translate(-50%,-50%) scale(1) rotate(-5deg)'},{opacity:0,transform:'translate(-50%,-72%) scale(1.05) rotate(-5deg)'}],{duration:780,easing:'cubic-bezier(.18,.9,.22,1)'});
 const g=game.getBoundingClientRect(),from=pitchBall.style.transform||'none',to=`translate3d(${g.width*.50}px,${g.height*.43}px,0) scale(3.0) rotate(420deg)`;pitchBall.style.display='block';pitchBall.style.opacity='1';
 const launch=pitchBall.animate?pitchBall.animate([{transform:from,filter:'brightness(1)'},{offset:.3,filter:'brightness(1.8) drop-shadow(0 0 14px #fff)'},{transform:to,filter:'brightness(1.25) drop-shadow(0 0 22px #fff)'}],{duration:520,easing:'cubic-bezier(.15,.87,.2,1)',fill:'forwards'}):null;
 await wait(92);frame(5);await wait(105);frame(6);batScene.classList.remove('shake');
 await wait(80);batScene.classList.add('zoomAway');await wait(70);flightScene.classList.add('active');flightBall.style.opacity='0';ballComet.style.opacity='0';
 await wait(130);pitchBall.style.opacity='0';flightBall.style.opacity='1';ballComet.style.opacity='.95';if(launch)launch.cancel();await wait(80);startFlight(error)
}
function startFlight(error){setPhase('flight');distance=0;score=Math.round(450+(1-error/.17)*650);scoreNum.textContent=score.toLocaleString();distanceNum.textContent='0m';steerHint.style.opacity='1';flightStart=performance.now();spawnPickups();cancelAnimationFrame(raf);raf=requestAnimationFrame(flightLoop)}
const assetCuts={meat:[30,55,105,92,'お肉'],star:[135,50,92,100,'スター'],coin:[230,48,92,100,'コイン'],x2:[325,48,103,100,'2倍'],boost:[432,40,112,120,'ブースト']};
function makeAssetDiv(type){const [x,y,w,h,label]=assetCuts[type],d=document.createElement('div');d.className='pickupSprite';d.setAttribute('aria-label',label);d.style.width=w+'px';d.style.height=h+'px';d.style.backgroundImage="url('1BE24540-08C9-4A78-AF0E-C366AAA666C6.png')";d.style.backgroundSize='1448px 1086px';d.style.backgroundPosition=`-${x}px -${y}px`;d.style.backgroundRepeat='no-repeat';const s=Math.min(76/w,76/h);d.style.transform=`scale(${s})`;return d}
function spawnPickups(){const specs=[['star',.26,.30,1.05],['meat',.70,.34,1.65],['coin',.38,.27,2.20],['x2',.77,.30,2.80],['star',.20,.25,3.35],['boost',.56,.32,3.85],['meat',.80,.25,4.45],['star',.34,.29,5.00]];for(const [type,x,y,t] of specs){const e=document.createElement('div');e.className='pickup pickup-'+type;e.appendChild(makeAssetDiv(type));pickups.appendChild(e);pickupData.push({e,type,x,y,t,hit:false})}}
function flightLoop(now){if(phase!=='flight')return;const elapsed=(now-flightStart)/1000,p=Math.min(1,elapsed/(flightDur/1000));distance=Math.floor(p*188);distanceNum.textContent=distance+'m';ballX+=(targetX-ballX)*.13;ballY+=(targetY-ballY)*.11;const px=ballX*100,py=ballY*100;flightBall.style.left=px+'%';flightBall.style.top=py+'%';flightBall.style.transform=`translate(-50%,-50%) rotate(${(targetX-ballX)*250}deg) scale(${1+.055*Math.sin(now/85)})`;ballComet.style.left=px+'%';ballComet.style.top=py+'%';farClouds.style.transform=`translate3d(${(0.5-ballX)*50}px,${elapsed*18}px,0) scale(${1+p*.22})`;mountainLayer.style.transform=`translate3d(${(0.5-ballX)*88}px,${elapsed*32}px,0) scale(${1+p*.38})`;cityLayer.style.transform=`translate3d(${(0.5-ballX)*125}px,${elapsed*49}px,0) scale(${1+p*.54})`;treeLayer.style.transform=`translate3d(${(0.5-ballX)*170}px,${elapsed*70}px,0) scale(${1+p*.74})`;if(groundLayer)groundLayer.style.transform=`perspective(250px) rotateX(36deg) translate3d(${(0.5-ballX)*195}px,${elapsed*86}px,0) scale(${1+p*.88})`;
 for(const o of pickupData){if(o.hit)continue;const dt=elapsed-o.t;if(dt < -1.35)continue;const progress=Math.max(0,Math.min(1,(dt+1.35)/2.1)),top=18+progress*70,scale=.45+progress*1.05;o.e.style.display='grid';o.e.style.left=(o.x*100)+'%';o.e.style.top=top+'%';o.e.style.transform=`translate(-50%,-50%) scale(${scale})`;o.e.style.opacity=String(Math.min(1,progress*2.2));if(progress>.48&&progress<.92){const dx=o.x-ballX,dy=(top/100)-ballY;if(Math.hypot(dx,dy)<.12)collect(o)}if(progress>=1){o.hit=true;o.e.style.opacity='0'}}
 if(p>=1){land();return}raf=requestAnimationFrame(flightLoop)}
function collect(o){o.hit=true;o.e.classList.add('hit');let text='GET!';if(o.type==='meat'){meat++;score+=220;text='🍖 お肉GET!'}else if(o.type==='star'){stars++;score+=180;text='⭐ STAR!'}else if(o.type==='coin'){score+=120;text='🪙 +120'}else if(o.type==='x2'){score*=2;text='×2 BONUS!'}else if(o.type==='boost'){score+=350;text='BOOST!!';flightBall.classList.add('boost');setTimeout(()=>flightBall.classList.remove('boost'),800)}scoreNum.textContent=Math.round(score).toLocaleString();pickupText.textContent=text;resetAnim(pickupText,'go');tone(620+(meat+stars)*55,.07,'triangle',.045)}
async function land(){cancelAnimationFrame(raf);setPhase('land');steerHint.style.opacity='0';pickups.style.opacity='.25';flightBall.style.transition='left .38s ease-in,top .48s cubic-bezier(.45,0,1,.45),transform .48s';flightBall.style.left='50%';flightBall.style.top='82%';flightBall.style.transform='translate(-50%,-50%) scale(.32) rotate(260deg)';if(groundLayer)groundLayer.animate([{filter:'brightness(1)'},{filter:'brightness(.75)',transform:'perspective(250px) rotateX(36deg) scale(1.15)'}],{duration:480,easing:'ease-in',fill:'forwards'});await wait(455);flightBall.style.opacity='0';resetAnim(flightScene,'land');resetAnim(landingDust,'go');resetAnim(landText,'go');tone(92,.24,'sawtooth',.09);await wait(950);showResult()}
function showResult(){setPhase('idle');resultDistance.textContent=distance+'m';resultScore.textContent=Math.round(score).toLocaleString();resultMeat.textContent=meat;resultStar.textContent=stars;intro.style.display='none';result.style.display='block';startBtn.textContent='⚾ もう一球！';overlay.classList.remove('hidden')}
function resetScenes(){batScene.className='scene';flightScene.className='scene';flightBall.style.cssText='';ballComet.style.cssText='';pitchBall.style.opacity='1';pickups.style.opacity='1';tiraWrap.className='breathe';hint.style.opacity='1';flash.classList.remove('go');impactBurst.classList.remove('go');kakiin.classList.remove('go');landingDust.classList.remove('go');landText.classList.remove('go');pickups.innerHTML='';[farClouds,mountainLayer,cityLayer,treeLayer,groundLayer].forEach(x=>{if(x){x.style.transform='';x.style.filter=''}});frame(0)}
function begin(){cancelAnimationFrame(raf);resetScenes();overlay.classList.add('hidden');intro.style.display='block';result.style.display='none';startBtn.textContent='⚾ 1球いってみる！';setTimeout(startPitch,420)}
function steer(clientX,clientY){if(phase!=='flight')return;const r=game.getBoundingClientRect();targetX=Math.max(.14,Math.min(.86,(clientX-r.left)/r.width));targetY=Math.max(.30,Math.min(.73,(clientY-r.top)/r.height))}
startBtn.addEventListener('click',begin);swingBtn.addEventListener('click',e=>{e.stopPropagation();doSwing()});batScene.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;doSwing()});flightScene.addEventListener('pointerdown',e=>{lastPointer=e.pointerId;flightScene.setPointerCapture?.(e.pointerId);steer(e.clientX,e.clientY)});flightScene.addEventListener('pointermove',e=>{if(lastPointer===e.pointerId)steer(e.clientX,e.clientY)});flightScene.addEventListener('pointerup',e=>{if(lastPointer===e.pointerId)lastPointer=null});window.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&phase==='pitch'){e.preventDefault();doSwing()}else if(phase==='flight'){if(e.code==='ArrowLeft')targetX=Math.max(.14,targetX-.07);if(e.code==='ArrowRight')targetX=Math.min(.86,targetX+.07);if(e.code==='ArrowUp')targetY=Math.max(.30,targetY-.05);if(e.code==='ArrowDown')targetY=Math.min(.73,targetY+.05)}});frame(0);
})();