(()=>{
'use strict';
const $=s=>document.querySelector(s), game=$('#game'), batScene=$('#batScene'), flightScene=$('#flightScene'), overlay=$('#overlay');
const tira=$('#tira'),tiraWrap=$('#tiraWrap'),pitcher=$('#pitcher'),pitchBall=$('#pitchBall'),trail=$('#trail'),swingBtn=$('#swingBtn'),hint=$('#hint'),batStatus=$('#batStatus');
const impactBurst=$('#impactBurst'),flash=$('#flash'),kakiin=$('#kakiin'),flightBall=$('#flightBall'),ballComet=$('#ballComet'),pickups=$('#pickups');
const distanceNum=$('#distanceNum'),scoreNum=$('#scoreNum'),pickupText=$('#pickupText'),landingDust=$('#landingDust'),landText=$('#landText');
const intro=$('#intro'),result=$('#result'),startBtn=$('#startBtn'),resultDistance=$('#resultDistance'),resultScore=$('#resultScore'),resultMeat=$('#resultMeat'),resultStar=$('#resultStar');
const farClouds=$('#farClouds'), mountainLayer=$('#mountainLayer'), cityLayer=$('#cityLayer'), treeLayer=$('#treeLayer'), groundLayer=$('#groundLayer');
let phase='idle',raf=0,pitchStart=0,pitchDur=1050,pitchP=0,score=0,meat=0,stars=0,distance=0,flightStart=0,flightDur=6100,targetX=.5,targetY=.54,ballX=.5,ballY=.54,lastPointer=null,audioCtx=null,pickupData=[];
const positions=[['0%','0%'],['33.333%','0%'],['66.667%','0%'],['100%','0%'],['0%','100%'],['33.333%','100%'],['66.667%','100%'],['100%','100%']];
function frame(i){const p=positions[i]||positions[0];tira.style.backgroundPosition=p[0]+' '+p[1];}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}
function tone(freq=440,time=.08,type='sine',vol=.05){try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+time);o.stop(audioCtx.currentTime+time)}catch(e){}}
function hitSound(){tone(520,.07,'square',.07);setTimeout(()=>tone(830,.11,'triangle',.06),45);setTimeout(()=>tone(1180,.15,'sine',.035),90)}
function resetAnim(el,cls){el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function setPhase(p){phase=p;batStatus.textContent=p==='pitch'?'PITCH!':p==='hit'?'IMPACT!':p==='flight'?'FLYING!':p==='land'?'LANDING':'READY'}
function pitchPos(p){const g=game.getBoundingClientRect(),pr=pitcher.getBoundingClientRect(),tr=tiraWrap.getBoundingClientRect();const x=(pr.left-g.left)+pr.width*.73+((tr.left-g.left)+tr.width*.34-((pr.left-g.left)+pr.width*.73))*p;const y=(pr.top-g.top)+pr.height*.52+((tr.top-g.top)+tr.height*.50-((pr.top-g.top)+pr.height*.52))*p-Math.sin(Math.PI*p)*24;const scale=.52+p*.58;pitchBall.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`;const tx=(pr.left-g.left)+pr.width*.66,ty=(pr.top-g.top)+pr.height*.56;const dx=x-tx,dy=y-ty,len=Math.sqrt(dx*dx+dy*dy);trail.style.left=tx+'px';trail.style.top=ty+'px';trail.style.width=Math.max(20,len-20)+'px';trail.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;trail.style.opacity=String(Math.min(.72,p*.9));}
function pitchLoop(now){if(phase!=='pitch')return;pitchP=Math.max(0,Math.min(1,(now-pitchStart)/pitchDur));pitchPos(pitchP);if(pitchP>=1){miss('見逃し！');return}raf=requestAnimationFrame(pitchLoop)}
async function startPitch(){setPhase('pitch');score=meat=stars=distance=0;scoreNum.textContent='0';distanceNum.textContent='0m';targetX=ballX=.5;targetY=ballY=.54;pickupData=[];pickups.innerHTML='';frame(0);tiraWrap.className='breathe';pitchBall.style.display='block';pitchBall.style.opacity='1';trail.style.opacity='0';swingBtn.disabled=true;hint.textContent='ピッチャー、振りかぶった！';resetAnim(pitcher,'windup');await wait(280);frame(1);tiraWrap.className='prep';await wait(170);swingBtn.disabled=false;hint.textContent='いまだと思ったらタップ！';pitchStart=performance.now();pitchPos(0);cancelAnimationFrame(raf);raf=requestAnimationFrame(pitchLoop)}
function doSwing(){if(phase!=='pitch')return;const d=Math.abs(pitchP-.86);swingBtn.disabled=true;if(d>.17){frame(3);tiraWrap.className='impact';tone(155,.09,'sawtooth',.04);setTimeout(()=>miss(pitchP<.86?'早い！':'遅い！'),180);return}cinematicHit(d)}
async function miss(text){if(phase==='idle')return;cancelAnimationFrame(raf);setPhase('idle');pitchBall.style.display='none';trail.style.opacity='0';frame(6);tiraWrap.className='';hint.textContent=text+'　もう一回！';tone(170,.12,'triangle',.04);await wait(650);intro.style.display='block';result.style.display='none';startBtn.textContent='⚾ もう一球！';overlay.classList.remove('hidden')}
async function cinematicHit(error){
 cancelAnimationFrame(raf);setPhase('hit');trail.style.opacity='0';frame(4);tiraWrap.className='impact';
 resetAnim(flash,'go');resetAnim(impactBurst,'go');resetAnim(kakiin,'go');resetAnim(batScene,'shake');hitSound();
 if(kakiin.animate)kakiin.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.35) rotate(-10deg)'},{opacity:1,offset:.16,transform:'translate(-50%,-50%) scale(1.18) rotate(-5deg)'},{opacity:1,offset:.72,transform:'translate(-50%,-50%) scale(1) rotate(-5deg)'},{opacity:0,transform:'translate(-50%,-70%) scale(1.06) rotate(-5deg)'}],{duration:760,easing:'cubic-bezier(.18,.9,.22,1)'});
 if(impactBurst.animate)impactBurst.animate([{opacity:1,transform:'translate(-50%,-50%) scale(.2) rotate(-8deg)'},{opacity:1,offset:.45,transform:'translate(-50%,-50%) scale(1.22) rotate(8deg)'},{opacity:0,transform:'translate(-50%,-50%) scale(1.7) rotate(15deg)'}],{duration:300,easing:'ease-out'});
 const g=game.getBoundingClientRect(),from=pitchBall.style.transform||'none',to=`translate3d(${g.width*.49}px,${g.height*.40}px,0) scale(2.8) rotate(360deg)`;
 pitchBall.style.display='block';pitchBall.style.opacity='1';
 const launch=pitchBall.animate?pitchBall.animate([{transform:from,filter:'brightness(1)'},{transform:to,filter:'brightness(1.4) drop-shadow(0 0 18px #fff)'}],{duration:520,easing:'cubic-bezier(.16,.88,.18,1)',fill:'forwards'}):null;
 await wait(82);frame(3);await wait(95);frame(5);hint.style.opacity='0';await wait(120);frame(6);batScene.classList.remove('shake');
 await wait(65);batScene.classList.add('zoomAway');flightScene.classList.add('active');flightBall.style.opacity='0';ballComet.style.opacity='0';
 await wait(150);pitchBall.style.opacity='0';flightBall.style.opacity='1';ballComet.style.opacity='.9';
 if(launch)launch.cancel();await wait(130);startFlight(error)
}
function startFlight(error){setPhase('flight');distance=0;score=Math.round(450+(1-error/.17)*650);scoreNum.textContent=score.toLocaleString();distanceNum.textContent='0m';steerHint.style.opacity='1';flightStart=performance.now();spawnPickups();cancelAnimationFrame(raf);raf=requestAnimationFrame(flightLoop)}
function makeAssetSvg(x,y,w,h,label){const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('aria-label',label);svg.setAttribute('preserveAspectRatio','xMidYMid meet');const img=document.createElementNS(ns,'image');img.setAttribute('href','1BE24540-08C9-4A78-AF0E-C366AAA666C6.png');img.setAttribute('x',String(-x));img.setAttribute('y',String(-y));img.setAttribute('width','1448');img.setAttribute('height','1086');svg.appendChild(img);return svg}
const assetCuts={meat:[26,38,108,122,'お肉'],star:[126,36,100,124,'スター'],coin:[221,39,100,120,'コイン'],x2:[320,38,105,124,'2倍リング'],boost:[420,31,116,133,'ブースト']};
function spawnPickups(){const specs=[['star',.25,.30,1.15],['meat',.70,.36,1.70],['coin',.40,.23,2.20],['x2',.78,.31,2.85],['star',.20,.25,3.35],['boost',.55,.33,3.90],['meat',.82,.24,4.45],['star',.33,.27,4.95]];for(const [type,x,y,t] of specs){const e=document.createElement('div');e.className='pickup';const c=assetCuts[type];e.appendChild(makeAssetSvg(...c));pickups.appendChild(e);pickupData.push({e,type,x,y,t,hit:false})}}
function flightLoop(now){if(phase!=='flight')return;const elapsed=(now-flightStart)/1000,p=Math.min(1,elapsed/(flightDur/1000));distance=Math.floor(p*188);distanceNum.textContent=distance+'m';ballX+=(targetX-ballX)*.13;ballY+=(targetY-ballY)*.11;const px=ballX*100,py=ballY*100;flightBall.style.left=px+'%';flightBall.style.top=py+'%';flightBall.style.transform=`translate(-50%,-50%) rotate(${(targetX-ballX)*260}deg) scale(${1+.06*Math.sin(now/90)})`;ballComet.style.left=px+'%';ballComet.style.top=py+'%';farClouds.style.transform=`translate3d(${(0.5-ballX)*45}px,${elapsed*17}px,0) scale(${1+p*.22})`;mountainLayer.style.transform=`translate3d(${(0.5-ballX)*82}px,${elapsed*31}px,0) scale(${1+p*.36})`;cityLayer.style.transform=`translate3d(${(0.5-ballX)*120}px,${elapsed*47}px,0) scale(${1+p*.52})`;treeLayer.style.transform=`translate3d(${(0.5-ballX)*165}px,${elapsed*67}px,0) scale(${1+p*.72})`;if(groundLayer)groundLayer.style.transform=`perspective(250px) rotateX(36deg) translate3d(${(0.5-ballX)*190}px,${elapsed*82}px,0) scale(${1+p*.84})`;
 for(const o of pickupData){if(o.hit)continue;const dt=elapsed-o.t;const depth=Math.max(0,Math.min(1,(dt+1.3)/1.3));const top=(o.y*100)+(dt*45);const scale=.35+depth*1.05;o.e.style.left=(o.x*100)+'%';o.e.style.top=top+'%';o.e.style.transform=`translate(-50%,-50%) scale(${scale})`;o.e.style.opacity=String(Math.max(0,Math.min(1,depth*1.8)));if(depth>.58){const dx=o.x-ballX,dy=(top/100)-ballY;if(Math.hypot(dx,dy)<.115)collect(o)}if(dt>1.0){o.hit=true;o.e.style.opacity='0'}}
 if(p>=1){land();return}raf=requestAnimationFrame(flightLoop)}
function collect(o){o.hit=true;o.e.classList.add('hit');let text='GET!';if(o.type==='meat'){meat++;score+=220;text='🍖 お肉GET!'}else if(o.type==='star'){stars++;score+=180;text='⭐ STAR!'}else if(o.type==='coin'){score+=120;text='🪙 +120'}else if(o.type==='x2'){score*=2;text='×2 BONUS!'}else if(o.type==='boost'){score+=350;text='BOOST!!';flightBall.classList.add('boost');setTimeout(()=>flightBall.classList.remove('boost'),800)}scoreNum.textContent=Math.round(score).toLocaleString();pickupText.textContent=text;resetAnim(pickupText,'go');tone(620+(meat+stars)*55,.07,'triangle',.045)}
async function land(){cancelAnimationFrame(raf);setPhase('land');steerHint.style.opacity='0';flightBall.style.transition='top .46s cubic-bezier(.45,0,1,.45),transform .46s';flightBall.style.top='80%';flightBall.style.transform='translate(-50%,-50%) scale(.38) rotate(220deg)';await wait(430);flightBall.style.opacity='0';resetAnim(flightScene,'land');resetAnim(landingDust,'go');resetAnim(landText,'go');if(landingDust.animate)landingDust.animate([{opacity:0,transform:'translateX(-50%) scale(.2)'},{opacity:1,offset:.25,transform:'translateX(-50%) scale(1.15)'},{opacity:0,transform:'translateX(-50%) scale(1.9) translateY(-15px)'}],{duration:900,easing:'ease-out'});if(landText.animate)landText.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.4)'},{opacity:1,offset:.15,transform:'translate(-50%,-50%) scale(1.2)'},{opacity:1,offset:.7,transform:'translate(-50%,-50%) scale(1)'},{opacity:0,transform:'translate(-50%,-70%) scale(.9)'}],{duration:1000,easing:'ease-out'});tone(95,.22,'sawtooth',.09);await wait(900);showResult()}
function showResult(){setPhase('idle');resultDistance.textContent=distance+'m';resultScore.textContent=Math.round(score).toLocaleString();resultMeat.textContent=meat;resultStar.textContent=stars;intro.style.display='none';result.style.display='block';startBtn.textContent='⚾ もう一球！';overlay.classList.remove('hidden')}
function resetScenes(){batScene.className='scene';flightScene.className='scene';flightBall.style.cssText='';ballComet.style.cssText='';pitchBall.style.opacity='1';tiraWrap.className='breathe';hint.style.opacity='1';flash.classList.remove('go');impactBurst.classList.remove('go');kakiin.classList.remove('go');landingDust.classList.remove('go');landText.classList.remove('go');pickups.innerHTML='';frame(0)}
function begin(){cancelAnimationFrame(raf);resetScenes();overlay.classList.add('hidden');intro.style.display='block';result.style.display='none';startBtn.textContent='⚾ 1球いってみる！';setTimeout(startPitch,420)}
function steer(clientX,clientY){if(phase!=='flight')return;const r=game.getBoundingClientRect();targetX=Math.max(.15,Math.min(.85,(clientX-r.left)/r.width));targetY=Math.max(.30,Math.min(.72,(clientY-r.top)/r.height))}
startBtn.addEventListener('click',begin);swingBtn.addEventListener('click',e=>{e.stopPropagation();doSwing()});batScene.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;doSwing()});flightScene.addEventListener('pointerdown',e=>{lastPointer=e.pointerId;flightScene.setPointerCapture?.(e.pointerId);steer(e.clientX,e.clientY)});flightScene.addEventListener('pointermove',e=>{if(lastPointer===e.pointerId)steer(e.clientX,e.clientY)});flightScene.addEventListener('pointerup',e=>{if(lastPointer===e.pointerId)lastPointer=null});window.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&phase==='pitch'){e.preventDefault();doSwing()}else if(phase==='flight'){if(e.code==='ArrowLeft')targetX=Math.max(.15,targetX-.07);if(e.code==='ArrowRight')targetX=Math.min(.85,targetX+.07);if(e.code==='ArrowUp')targetY=Math.max(.30,targetY-.05);if(e.code==='ArrowDown')targetY=Math.min(.72,targetY+.05)}});frame(0);
})();